name: Close duplicates
on:
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: iv-org/close-potential-duplicates@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Issue title filter work with anymatch https://www.npmjs.com/package/anymatch.
          # Any matched issue will stop detection immediately.
          # You can specify multi filters in each line.
          filter: ''
          # Exclude keywords in title before detecting.
          exclude: ''
          # Label to set, when potential duplicates are detected.
          label: duplicate
          # Get issues with state to compare. Supported state: 'all', 'closed', 'open'.
          state: open
          # If similarity is higher than this threshold([0,1]), issue will be marked as duplicate.
          threshold: 0.9
          # Reactions to be add to comment when potential duplicates are detected.
          # Available reactions: "-1", "+1", "confused", "laugh", "heart", "hooray", "rocket", "eyes"
          reactions: ''
          close: true
          # Comment to post when potential duplicates are detected.
          comment: |
            Hello, your issue is a duplicate of this/these issue(s): {{#issues}}
              - #{{ number }} [accuracy: {{ accuracy }}%]
            {{/issues}}
            
            If this is a mistake please explain why and ping @\ImSwordQueen.
            
            Please refrain from opening new issues, it won't help in solving your problem.
